services:
  scraper:
    container_name: autoria-scraper
    restart: always
    build: .
    environment:
      DATABASE__URL: $DATABASE__URL
      SCRAPER__PAGES_LIMIT: $SCRAPER__PAGES_LIMIT
      SCRAPER__ROOT_URL: $SCRAPER__ROOT_URL
      SCRAPER__PHONE_URL: $SCRAPER__PHONE_URL
      SCRAPER__BATCH_SIZE: $SCRAPER__BATCH_SIZE
      SCRAPER__AIOHTTP__TIMEOUT: $SCRAPER__AIOHTTP__TIMEOUT
      SCRAPER__AIOHTTP__ATTEMPTS_LIMIT: $SCRAPER__AIOHTTP__ATTEMPTS_LIMIT
      SCRAPER__AIOHTTP__ATTEMPT_DELAY: $SCRAPER__AIOHTTP__ATTEMPT_DELAY
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: autoria-postgres
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
