services:
  scraper:
    container_name: autoria-scraper
    restart: always
    build: .
    environment:
      # each in cron format: "* * * * *"
      # https://crontab.guru/
      CRON__PG_DUMP: $CRON__PG_DUMP
      CRON__SCRAPER: $CRON__SCRAPER

      # For pg_dump via cron
      PG_USER: $PG_USER
      PG_HOST: $PG_HOST
      PG_PASSWORD: $PG_PASSWORD
      PG_DB: $PG_DB

      # Scraper settings
      DATABASE__URL: $DATABASE__URL
      SCRAPER__PAGES_LIMIT: $SCRAPER__PAGES_LIMIT
      SCRAPER__ROOT_URL: $SCRAPER__ROOT_URL
      SCRAPER__PHONE_URL: $SCRAPER__PHONE_URL
      SCRAPER__BATCH_SIZE: $SCRAPER__BATCH_SIZE
      SCRAPER__AIOHTTP__TIMEOUT: $SCRAPER__AIOHTTP__TIMEOUT
      SCRAPER__AIOHTTP__ATTEMPTS_LIMIT: $SCRAPER__AIOHTTP__ATTEMPTS_LIMIT
      SCRAPER__AIOHTTP__ATTEMPT_DELAY: $SCRAPER__AIOHTTP__ATTEMPT_DELAY
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15.13
    container_name: autoria-postgres
    restart: always
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
